const PDFDocument = require('pdfkit');

function drawAgendaHeader(doc, y) {
  const colX = [30, 50, 115, 150, 230, 370, 450];
  const colW = [20, 65, 35, 80, 140, 80, 115];
  const primaryColor = '#7C3AED';

  doc.rect(30, y, 535, 18).fill(primaryColor);
  doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold');

  const headers = ['#', 'Time', 'Min', 'Area', 'Activity', 'PIC / Presenter', 'Support / Attendees'];
  headers.forEach((h, i) => {
    doc.text(h, colX[i] + 3, y + 5, { width: colW[i] - 6, align: i === 2 ? 'center' : 'left' });
  });

  return y + 18;
}

function drawVisitorHeader(doc, y) {
  const vColX = [30, 55, 180, 305, 435];
  const vColW = [25, 125, 125, 130, 130];

  doc.rect(30, y, 535, 18).fill('#4C1D95');
  doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold');

  const vHeaders = ['#', 'Name & Title', 'Designation', 'Company', 'Department'];
  vHeaders.forEach((h, i) => {
    doc.text(h, vColX[i] + 3, y + 5, { width: vColW[i] - 6 });
  });

  return y + 18;
}

function generateAgendaPdfBuffer(visit) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 30, size: 'A4', bufferPages: true });
      const buffers = [];

      doc.on('data', chunk => buffers.push(chunk));
      doc.on('end', () => {
        // Add footer & page numbers to all generated pages
        const pages = doc.bufferedPageRange();
        for (let i = 0; i < pages.count; i++) {
          doc.switchToPage(i);
          doc.fontSize(8).font('Helvetica').fillColor('#94A3B8').text(
            `Generated by TIEI Visitor Management System • Toyota Industries Engine India • Page ${i + 1} of ${pages.count}`,
            30, 810, { align: 'center', width: 535 }
          );
        }
        resolve(Buffer.concat(buffers));
      });
      doc.on('error', err => reject(err));

      const primaryColor = '#7C3AED';
      const darkColor = '#0F172A';
      const mutedColor = '#64748B';
      const lightBg = '#F8FAFC';

      const visitors = visit.visitors || [];
      const agenda = visit.agenda || [];
      const refId = `TIEI-VIS-${(visit.visit_date || '').replace(/-/g, '')}-${(visit._id || visit.id || '').toString().slice(-4).toUpperCase()}`;

      // ── Header Banner ──
      doc.rect(30, 30, 535, 54).fill('#1E1B4B');
      
      doc.fillColor('#FFFFFF').fontSize(16).font('Helvetica-Bold').text('TOYOTA INDUSTRIES ENGINE INDIA', 42, 40);
      doc.fontSize(10).font('Helvetica').text('VISITOR INSTRUCTION SHEET & PLANT TOUR AGENDA', 42, 60);

      doc.fontSize(10).font('Helvetica-Bold').fillColor('#C4B5FD').text(`Ref: ${refId}`, 400, 48, { align: 'right', width: 150 });

      let y = 96;

      // ── Overview Details Box ──
      doc.rect(30, y, 535, 66).fill(lightBg).stroke('#E2E8F0');
      
      doc.fillColor(darkColor).fontSize(9).font('Helvetica-Bold');
      doc.text('Company:', 42, y + 10);
      doc.font('Helvetica').text(visit.company_name || '—', 95, y + 10);

      doc.font('Helvetica-Bold').text('Date:', 320, y + 10);
      doc.font('Helvetica').text(visit.visit_date || '—', 355, y + 10);

      doc.font('Helvetica-Bold').text('Time Slot:', 42, y + 28);
      doc.font('Helvetica').text(`${visit.visit_start || '09:00'} - ${visit.visit_end || '17:00'}`, 95, y + 28);

      doc.font('Helvetica-Bold').text('Visit Advisor:', 320, y + 28);
      doc.font('Helvetica').text(visit.visit_advisor || '—', 390, y + 28);

      doc.font('Helvetica-Bold').text('Visit No.:', 42, y + 46);
      doc.font('Helvetica').text(visit.visit_no || '1st', 95, y + 46);

      doc.font('Helvetica-Bold').text('Purpose:', 200, y + 46);
      doc.font('Helvetica').text(visit.visit_purpose || '—', 250, y + 46, { width: 300 });

      y += 82;

      // ── 1. VISITOR DELEGATION LIST ──
      doc.fillColor(primaryColor).fontSize(11).font('Helvetica-Bold').text(`VISITOR DELEGATION LIST (${visitors.length})`, 30, y);
      y += 16;

      const vColX = [30, 55, 180, 305, 435];
      const vColW = [25, 125, 125, 130, 130];

      y = drawVisitorHeader(doc, y);

      if (visitors.length === 0) {
        doc.rect(30, y, 535, 18).fill('#FFFFFF').stroke('#E2E8F0');
        doc.fillColor(mutedColor).fontSize(8).font('Helvetica').text('No visitor attendees recorded', 35, y + 5);
        y += 18;
      } else {
        visitors.forEach((v, idx) => {
          const vItems = [
            String(idx + 1),
            `${v.title || 'Mr'} ${v.name || '—'}`,
            v.designation || '—',
            v.company || '—',
            v.dept || '—'
          ];

          doc.fontSize(8).font('Helvetica');
          let rowH = 16;
          vItems.forEach((txt, i) => {
            const h = doc.heightOfString(txt, { width: vColW[i] - 6 });
            if (h + 8 > rowH) rowH = h + 8;
          });

          if (y + rowH > 750) {
            doc.addPage();
            y = 40;
            doc.fillColor(primaryColor).fontSize(10).font('Helvetica-Bold').text('VISITOR DELEGATION LIST (Contd.)', 30, y);
            y += 15;
            y = drawVisitorHeader(doc, y);
          }

          const bg = idx % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
          doc.rect(30, y, 535, rowH).fill(bg).stroke('#E2E8F0');

          doc.fillColor(darkColor).fontSize(8).font('Helvetica');
          doc.text(vItems[0], vColX[0] + 3, y + 4, { width: vColW[0] - 6 });
          
          doc.font('Helvetica-Bold');
          doc.text(vItems[1], vColX[1] + 3, y + 4, { width: vColW[1] - 6 });
          
          doc.font('Helvetica');
          doc.text(vItems[2], vColX[2] + 3, y + 4, { width: vColW[2] - 6 });
          doc.text(vItems[3], vColX[3] + 3, y + 4, { width: vColW[3] - 6 });
          doc.text(vItems[4], vColX[4] + 3, y + 4, { width: vColW[4] - 6 });

          y += rowH;
        });
      }

      y += 20;

      // ── 2. PLANT TOUR SCHEDULE TABLE ──
      if (y > 680) {
        doc.addPage();
        y = 40;
      }

      doc.fillColor(primaryColor).fontSize(11).font('Helvetica-Bold').text('PLANT TOUR SCHEDULE', 30, y);
      y += 16;

      const colX = [30, 50, 115, 150, 230, 370, 450];
      const colW = [20, 65, 35, 80, 140, 80, 115];

      y = drawAgendaHeader(doc, y);

      // Table Rows
      if (agenda.length === 0) {
        doc.rect(30, y, 535, 18).fill('#FFFFFF').stroke('#E2E8F0');
        doc.fillColor(mutedColor).fontSize(8).font('Helvetica').text('No agenda items recorded', 35, y + 5);
        y += 18;
      } else {
        agenda.forEach((r, idx) => {
          const textItems = [
            String(idx + 1),
            `${r.from_time || '—'} - ${r.to_time || '—'}`,
            `${r.duration_min || 10}m`,
            r.area || '—',
            r.activity_name || '—',
            r.pic || '—',
            r.support_attendees || '—'
          ];

          doc.fontSize(8).font('Helvetica');
          let rowH = 16;
          textItems.forEach((txt, i) => {
            const h = doc.heightOfString(txt, { width: colW[i] - 6 });
            if (h + 8 > rowH) rowH = h + 8;
          });

          if (y + rowH > 750) {
            doc.addPage();
            y = 40;
            doc.fillColor(primaryColor).fontSize(10).font('Helvetica-Bold').text('PLANT TOUR SCHEDULE (Contd.)', 30, y);
            y += 15;
            y = drawAgendaHeader(doc, y);
          }

          const bg = idx % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
          doc.rect(30, y, 535, rowH).fill(bg).stroke('#E2E8F0');

          doc.fillColor(darkColor).fontSize(8).font('Helvetica');
          doc.text(textItems[0], colX[0] + 3, y + 4, { width: colW[0] - 6 });
          
          doc.font('Helvetica-Bold').fillColor(primaryColor);
          doc.text(textItems[1], colX[1] + 3, y + 4, { width: colW[1] - 6 });
          
          doc.font('Helvetica').fillColor(darkColor);
          doc.text(textItems[2], colX[2] + 3, y + 4, { width: colW[2] - 6, align: 'center' });
          
          doc.font('Helvetica-Bold');
          doc.text(textItems[3], colX[3] + 3, y + 4, { width: colW[3] - 6 });
          
          doc.font('Helvetica');
          doc.text(textItems[4], colX[4] + 3, y + 4, { width: colW[4] - 6 });
          doc.text(textItems[5], colX[5] + 3, y + 4, { width: colW[5] - 6 });
          
          doc.fillColor('#475569');
          doc.text(textItems[6], colX[6] + 3, y + 4, { width: colW[6] - 6 });

          y += rowH;
        });
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = {
  generateAgendaPdfBuffer
};
